name: Deploy SSH

on:
  push:
    branches: ["master"]
  # release:
  #   types: [created]

env:
  PROJECT_PATH: src/SGM.WebApp/SGM.WebApp.csproj
  DEPLOY_PATH: /var/www/sgm-main
  GOOGLE_SA_KEY: blog-suxrobgm-13a40292a9ba.json

jobs:
  deploy-main-app:
    name: Deploy Main App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -r linux-x64 -p:PublishSingleFile=true --output ./publish

      # - name: Add production config
      #   run: |
      #     echo '${{ secrets.API_APPSETTINGS }}' > ./publish/appsettings.Production.json

      - name: Stop service and clean
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop sgm-main.service
            rm -rf ${{ env.DEPLOY_PATH }}/*

      - name: Upload files
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./publish/*"
          target: ${{ env.DEPLOY_PATH }}

      - name: Move files from publish to deploy path
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mv ${{ env.DEPLOY_PATH }}/publish/* ${{ env.DEPLOY_PATH }}
            rm -rf ${{ env.DEPLOY_PATH }}/publish

      - name: Copy Google SA key into app
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ${{ env.DEPLOY_PATH }}/keys
            cp ./home/persistence/${{ env.GOOGLE_SA_KEY }} ${{ env.DEPLOY_PATH }}/keys/
            chown www-data:www-data ${{ env.DEPLOY_PATH }}/keys/${{ env.GOOGLE_SA_KEY }}
            chmod 640 ${{ env.DEPLOY_PATH }}/keys/${{ env.GOOGLE_SA_KEY }}

      - name: Copy appsettings Production
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cp ./home/persistence/appsettings.Production.json ${{ env.DEPLOY_PATH }}/appsettings.Production.json
            chown www-data:www-data ${{ env.DEPLOY_PATH }}/appsettings.Production.json
            chmod 640 ${{ env.DEPLOY_PATH }}/appsettings.Production.json

      - name: Restart service
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl start sgm-main.service
